export type Locale = "en" | "es";

export type Dict = typeof EN;

export const EN = {
  locale: "en" as Locale,
  htmlLang: "en-US",
  altHref: "/es",
  altLabel: "ES",
  cta: {
    bookNow: "Book now",
    bookAppointment: "Book your appointment",
    bookOnline: "Book online now",
    seeHow: "See how it works",
    seeMore: "See more on Instagram",
    follow: "Follow",
    callUs: "Or call us",
    whatsapp: "WhatsApp",
    chatWithUs: "Chat with us",
    sendWhatsapp: "Send WhatsApp",
    askZip: "Ask if we cover your zip",
    makeAppointment: "Make an appointment",
    bookDental: "Book dental cleaning",
    bookService: "Book this service",
  },
  nav: {
    about: "About",
    services: "Services",
    how: "How it works",
    coverage: "Coverage",
    reviews: "Reviews",
    faq: "FAQ",
  },
  hero: {
    badge: "Mobile spa · Miami & Broward",
    title1: "Spa-grade",
    title2: "grooming.",
    accent: "we come to your door",
    desc: "Door-to-door grooming spa for dogs & cats in Miami-Dade & Broward. Premium products. Gentle hands.",
    descStrong: "Zero transport stress.",
    rating: "Rating",
    area: "Service area",
    hours: "Hours",
    areaValue: "Miami-Dade & Parts of Broward",
  },
  marquee: ["★ Door-to-door", "★ No transport stress", "★ Premium products", "★ Miami & Broward", "★ 7 days a week", "★ No anesthesia dental"],
  stats: {
    happyPets: "Happy pets",
    fiveStar: "5★ Reviews",
    daysWeek: "Days a week",
    dailyWindow: "Daily window",
  },
  about: {
    eyebrow: "About us",
    title1: "Mobile pet care,",
    title2: "done right.",
    body: "We're a mobile pet care company based in Miami, Florida. We offer door-to-door service — and the assurance that your beloved fur babies are in the safest, most gentle, and professional hands.",
    bullets: [
      "We come to your home — no transport stress",
      "Premium products, gentle handling",
      "7 days a week, 8 AM to 6 PM",
    ],
    badgeLabel: "Happy pets",
  },
  services: {
    eyebrow: "Our services",
    title: "Spa-grade care, right at your door.",
    items: [
      { title: "Bath", desc: "Shampoo, conditioner, anal gland, ear cleaning, hair dryer, nail cut & grinding, sanitary trim, cologne." },
      { title: "Full Grooming", desc: "Everything in Bath, plus teeth brush and a full haircut. The complete spa.", featured: true, badge: "Most popular" },
      { title: "Non-Anesthetic Dental Cleaning", desc: "Professional dental cleaning with no sedation. Removes tartar and plaque for fresh breath and healthy gums. Starting at $150." },
      { title: "Extras", desc: "Nail Trim & Filing · Deshedding · Coat Recovery / De-matting — add-ons to complete the spa." },
    ],
  },
  how: {
    eyebrow: "How it works",
    title: "From booking to wagging tail.",
    sub: "Four steps, zero stress. We handle the rest.",
    steps: [
      { title: "Book online", desc: "Pick a date, service, and tell us about your pet. Takes 60 seconds." },
      { title: "We come to you", desc: "Our fully-equipped van pulls up at your door — no transport stress." },
      { title: "Spa session", desc: "Bath, grooming, or dental — gentle hands, premium products." },
      { title: "Happy pet", desc: "Clean, fresh and smelling great. We even send you photos." },
    ],
  },
  dental: {
    eyebrow: "Dental prophylaxis",
    title1: "No anesthesia,",
    title2: "no stress.",
    body: "Professional dental cleaning that doesn't require sedation. Safer, less invasive, and perfect for older pets or pets with health issues.",
    bullets: [
      "Eliminates bad breath",
      "Prevents plaque and tartar progression",
      "Prevents red, swollen gums that may bleed",
      "Avoids severe periodontitis & tooth loss",
      "Reduces risk of organ infections from bacteria",
    ],
    callout1: "No anesthesia",
    callout2: "Safer for older pets & those with health issues",
    price: "Starting at $150",
  },
  beforeAfter: {
    eyebrow: "Real results",
    title1: "See the",
    title2: "difference.",
    body: "Drag the slider to compare. Every session is photographed and shared with you.",
    note: "Photo report included with every appointment",
  },
  gallery: {
    eyebrow: "Instagram",
    title: "Latest from",
    handle: "@urbanmobilegrooming",
  },
  reviews: {
    eyebrow: "Reviews",
    title: "Loved by 250+ pet parents.",
    aggregate: "5.0 · 252 reviews",
  },
  area: {
    eyebrow: "Service area",
    title: "Where we roll.",
    body: "We cover all of Miami-Dade and parts of Broward — door-to-door. Not sure if we reach your block? Send us a quick message and we'll confirm in minutes.",
  },
  faq: {
    eyebrow: "FAQ",
    title: "Frequently asked.",
    sub: "Can't find what you're looking for?",
    cta: "Call 786-906-6700",
    items: [
      { q: "How does mobile grooming actually work?", a: "We bring a fully self-contained grooming van to your home. It has its own water, power, climate control, and a professional grooming station. We park in your driveway and groom your pet right outside while you stay inside." },
      { q: "Do I need to be home during the appointment?", a: "You don't have to stay, but there must be a responsible adult at the home to hand over your pet when we arrive and receive them when we're done. We'll text you when we arrive and when your pet is ready." },
      { q: "How long does a session take?", a: "Most full grooms take 60–90 minutes depending on coat condition and size. Bath & brush sessions are usually 45–60 minutes. We never rush." },
      { q: "Is it more expensive than a regular groomer?", a: "Slightly. You're paying for convenience, no cage time, one-on-one attention, and the comfort of your pet staying in their environment. Most clients say it's worth every penny." },
      { q: "What products do you use?", a: "We use Bio-Groom products — professional, high-quality shampoos and conditioners. We carry options for sensitive skin, anti-itch, deshedding, and whitening. Tell us about allergies or preferences when you book." },
      { q: "What if my dog is anxious or aggressive?", a: "We specialize in difficult cases. Our groomers are trained in low-stress handling. Many anxious dogs do dramatically better in our mobile environment than in a busy salon." },
      { q: "How do I book?", a: "Click 'Book now' anywhere on this page. Pick service, date, and confirm. We'll text you 24h before to confirm the time window." },
      { q: "Do you cover South Miami?", a: "Yes — we cover all of South Miami and the rest of Miami-Dade, plus parts of Broward. Check the coverage map above. If you don't see your area, message us — we may still be able to help." },
    ],
  },
  contact: {
    eyebrow: "Contact",
    title1: "Let's make your",
    title2: "pet's day.",
    body: "Ready to book a visit? Reach out — we typically respond same day.",
    serviceArea: "Service area",
    serviceAreaValue: "Miami-Dade & Parts of Broward",
    phone: "Phone",
    email: "Email",
    cardTitle: "Book your appointment.",
    cardBody: "Pick a service, date, and confirm in 60 seconds. We'll text you to confirm the time window.",
  },
  footer: {
    rights: "All rights reserved",
  },
};

export const ES: Dict = {
  locale: "es",
  htmlLang: "es-US",
  altHref: "/",
  altLabel: "EN",
  cta: {
    bookNow: "Reservar",
    bookAppointment: "Reserva tu cita",
    bookOnline: "Reservar online",
    seeHow: "Cómo funciona",
    seeMore: "Ver más en Instagram",
    follow: "Seguir",
    callUs: "O llámanos",
    whatsapp: "WhatsApp",
    chatWithUs: "Escríbenos",
    sendWhatsapp: "Enviar WhatsApp",
    askZip: "Pregunta si cubrimos tu zip",
    makeAppointment: "Hacer una cita",
    bookDental: "Reservar limpieza dental",
    bookService: "Reservar este servicio",
  },
  nav: {
    about: "Nosotros",
    services: "Servicios",
    how: "Cómo funciona",
    coverage: "Cobertura",
    reviews: "Reseñas",
    faq: "Preguntas",
  },
  hero: {
    badge: "Spa móvil · Miami y Broward",
    title1: "Grooming de",
    title2: "spa.",
    accent: "vamos hasta tu puerta",
    desc: "Spa móvil de grooming para perros y gatos en Miami-Dade y Broward. Productos premium. Manos suaves.",
    descStrong: "Cero estrés de transporte.",
    rating: "Rating",
    area: "Área de servicio",
    hours: "Horario",
    areaValue: "Miami-Dade y parte de Broward",
  },
  marquee: ["★ A domicilio", "★ Sin estrés de transporte", "★ Productos premium", "★ Miami y Broward", "★ 7 días a la semana", "★ Dental sin anestesia"],
  stats: {
    happyPets: "Mascotas felices",
    fiveStar: "Reseñas 5★",
    daysWeek: "Días a la semana",
    dailyWindow: "Ventana diaria",
  },
  about: {
    eyebrow: "Nosotros",
    title1: "Cuidado móvil",
    title2: "hecho bien.",
    body: "Somos una empresa de cuidado móvil con base en Miami, Florida. Ofrecemos servicio a domicilio — y la tranquilidad de que tus peluditos están en las manos más seguras, suaves y profesionales.",
    bullets: [
      "Vamos a tu casa — sin estrés de transporte",
      "Productos premium, manejo gentil",
      "7 días a la semana, 8 AM a 6 PM",
    ],
    badgeLabel: "Mascotas felices",
  },
  services: {
    eyebrow: "Nuestros servicios",
    title: "Cuidado de spa, en tu puerta.",
    items: [
      { title: "Baño", desc: "Shampoo, acondicionador, glándulas anales, limpieza de oídos, secado, corte y limado de uñas, sanitario, colonia." },
      { title: "Grooming Completo", desc: "Todo lo del Baño, más cepillado de dientes y corte de pelo completo. El spa completo.", featured: true, badge: "El más popular" },
      { title: "Limpieza Dental sin Anestesia", desc: "Limpieza dental profesional sin sedación. Remueve sarro y placa para aliento fresco y encías sanas. Desde $150." },
      { title: "Extras", desc: "Corte y limado de uñas · Deshedding · Recuperación de pelaje / Desenredado — extras para completar el spa." },
    ],
  },
  how: {
    eyebrow: "Cómo funciona",
    title: "De la reserva a la colita feliz.",
    sub: "Cuatro pasos, cero estrés. Nosotros nos encargamos.",
    steps: [
      { title: "Reserva online", desc: "Elige fecha, servicio y cuéntanos de tu mascota. 60 segundos." },
      { title: "Vamos hasta ti", desc: "Nuestro van totalmente equipado llega a tu puerta — sin estrés de transporte." },
      { title: "Sesión de spa", desc: "Baño, grooming o dental — manos suaves, productos premium." },
      { title: "Mascota feliz", desc: "Limpia, fresca y oliendo increíble. Te enviamos fotos." },
    ],
  },
  dental: {
    eyebrow: "Profilaxis dental",
    title1: "Sin anestesia,",
    title2: "sin estrés.",
    body: "Limpieza dental profesional que no requiere sedación. Más seguro, menos invasivo y perfecto para mascotas mayores o con condiciones de salud.",
    bullets: [
      "Elimina el mal aliento",
      "Previene placa y sarro",
      "Previene encías rojas e inflamadas que sangran",
      "Evita periodontitis severa y pérdida de dientes",
      "Reduce el riesgo de infecciones de órganos por bacterias",
    ],
    callout1: "Sin anestesia",
    callout2: "Más seguro para mascotas mayores o con condiciones",
    price: "Desde $150",
  },
  beforeAfter: {
    eyebrow: "Resultados reales",
    title1: "Mira la",
    title2: "diferencia.",
    body: "Arrastra el slider para comparar. Cada sesión se fotografía y compartimos contigo.",
    note: "Reporte fotográfico incluido en cada cita",
  },
  gallery: {
    eyebrow: "Instagram",
    title: "Lo último de",
    handle: "@urbanmobilegrooming",
  },
  reviews: {
    eyebrow: "Reseñas",
    title: "Amados por 250+ familias.",
    aggregate: "5.0 · 252 reseñas",
  },
  area: {
    eyebrow: "Área de servicio",
    title: "Donde llegamos.",
    body: "Cubrimos todo Miami-Dade y parte de Broward — a domicilio. ¿No estás seguro si llegamos a tu cuadra? Mándanos un mensaje y confirmamos en minutos.",
  },
  faq: {
    eyebrow: "Preguntas",
    title: "Preguntas frecuentes.",
    sub: "¿No encuentras lo que buscas?",
    cta: "Llama al 786-906-6700",
    items: [
      { q: "¿Cómo funciona el grooming móvil?", a: "Llevamos un van totalmente autosuficiente hasta tu casa. Tiene su propia agua, electricidad, aire acondicionado y una estación profesional de grooming. Nos estacionamos en tu entrada y bañamos a tu mascota afuera mientras tú te quedas dentro." },
      { q: "¿Necesito estar en casa durante la cita?", a: "No tienes que quedarte, pero debe haber un adulto responsable en la casa para entregarnos la mascota cuando llegamos y recibirla cuando terminamos. Te avisamos por mensaje cuando llegamos y cuando termina." },
      { q: "¿Cuánto dura una sesión?", a: "La mayoría de grooms completos toman 60–90 minutos según el pelaje y tamaño. Baños suelen ser 45–60 minutos. Nunca apuramos." },
      { q: "¿Es más caro que un groomer tradicional?", a: "Un poco. Pagas por la comodidad, sin tiempo en jaula, atención uno-a-uno y la tranquilidad de que tu mascota se queda en su ambiente. La mayoría dice que vale cada centavo." },
      { q: "¿Qué productos usan?", a: "Usamos productos Bio-Groom — shampoos y acondicionadores profesionales de alta calidad. Tenemos opciones para piel sensible, anti-rasquiña, deshedding y blanqueador. Cuéntanos de alergias o preferencias al reservar." },
      { q: "¿Y si mi perro es ansioso o agresivo?", a: "Nos especializamos en casos difíciles. Nuestros groomers están entrenados en manejo de bajo estrés. Muchos perros ansiosos rinden mucho mejor en nuestro ambiente móvil que en un salón ruidoso." },
      { q: "¿Cómo reservo?", a: "Haz clic en 'Reservar' en cualquier parte. Elige servicio, fecha y confirma. Te mandamos un mensaje 24h antes para confirmar la ventana de tiempo." },
      { q: "¿Cubren South Miami?", a: "Sí — cubrimos todo South Miami y el resto de Miami-Dade, además de parte de Broward. Mira el mapa de cobertura arriba. Si no ves tu área, escríbenos — tal vez aún podamos ayudar." },
    ],
  },
  contact: {
    eyebrow: "Contacto",
    title1: "Hagamos feliz",
    title2: "a tu mascota.",
    body: "¿Listo para reservar? Escríbenos — normalmente respondemos el mismo día.",
    serviceArea: "Área de servicio",
    serviceAreaValue: "Miami-Dade y parte de Broward",
    phone: "Teléfono",
    email: "Email",
    cardTitle: "Reserva tu cita.",
    cardBody: "Elige servicio, fecha y confirma en 60 segundos. Te mandamos mensaje para confirmar la hora.",
  },
  footer: {
    rights: "Todos los derechos reservados",
  },
};

export function getDict(locale: Locale): Dict {
  return locale === "es" ? ES : EN;
}
